Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: Linux_tc32_Build
+name: tc32_Cmake_Build
 
 # on: [push, pull_request]
 on: 
@@ -16,8 +16,9 @@ on:
           '825x_ble_remote 825x_ble_sample'
         required: true
         default: '825x_ble_sample'
+
 jobs:
-  Linux_CMake_Build:
+  Linux_CMake_Convert:
     runs-on: ubuntu-latest
     
     steps:
@@ -35,7 +36,7 @@ jobs:
       with:
         path: |
           cdt2cmake
-          tc32
+          # tc32
         key: ${{ runner.os }}-toolchain-tc32
         restore-keys: |
           ${{ runner.os }}-toolchain-tc32
@@ -43,13 +44,13 @@ jobs:
     - if: ${{ steps.Restore_Cached_Toolchain.outputs.cache-hit != 'true' }}
       name: download and decompression toolchain
       run: |
-        wget -O tc32_toolchains.tar https://wiki.telink-semi.cn/tools_and_sdk/others/tc32_toolchains.tar
-        tar xf tc32_toolchains.tar
-        ls
-        if [ $? != 0 ]; then
-          echo "download toolchain fail"
-          exit 1
-        fi
+        # wget -O tc32_toolchains.tar https://wiki.telink-semi.cn/tools_and_sdk/others/tc32_toolchains.tar
+        # tar xf tc32_toolchains.tar
+        # ls
+        # if [ $? != 0 ]; then
+        #   echo "download toolchain fail"
+        #   exit 1
+        # fi
         
         wget -O cdt2cmake_Linux_X64.tar.xz http://wiki.telink-semi.cn/tools_and_sdk/others/cdt2cmake_Linux_X64.tar.xz    
         tar xf cdt2cmake_Linux_X64.tar.xz
@@ -65,7 +66,7 @@ jobs:
       with:
         path: |
           cdt2cmake
-          tc32
+          # tc32
         key: ${{ runner.os }}-toolchain-tc32
 
     - name: convert cdt2cmake
@@ -73,6 +74,84 @@ jobs:
         echo "convert cdt2cmake"
         ./cdt2cmake/cdt2cmake ${{ github.event.inputs.cproject }}
 
+    # - name: cmake build
+    #   run: |
+    #     echo "cmake building..."
+    #     ls
+    #     cmake ./b85_ble_sdk -Bcmake_build -DTOOLCHAIN_PATH="`pwd`/tc32"
+    #     echo "parameter_name ${{ github.event.inputs.target }}"
+    #     cmake --build cmake_build --target "${{ github.event.inputs.target }}" -j16
+
+    # - name: upload artifacts
+    #   uses: actions/upload-artifact@v3
+    #   with:
+    #     name: build_artifact
+    #     path: |
+    #       cmake_build/${{ github.event.inputs.target }}*
+    #     retention-days: 3
+
+  
+  Windows_CMake_build:
+    runs-on: windows-latest
+      
+    steps:
+    - name: check parameters
+      run: |
+        echo "cproject ${{ github.event.inputs.cproject }}"
+        echo "target ${{ github.event.inputs.target }}"
+
+    - name: Checkout Repository
+      uses: actions/checkout@v3
+
+    - name: Restore Cached Toolchain
+      id: Restore_Cached_Toolchain
+      uses: actions/cache@v3
+      with:
+        path: |
+          cdt2cmake
+          # tc32
+        key: ${{ runner.os }}-toolchain-tc32
+        restore-keys: |
+          ${{ runner.os }}-toolchain-tc32
+     
+    - if: ${{ steps.Restore_Cached_Toolchain.outputs.cache-hit != 'true' }}
+      name: download and decompression toolchain
+      run: |
+        wget -O tc32_toolchains.tar https://wiki.telink-semi.cn/tools_and_sdk/others/tc32_toolchains.tar
+        tar xf tc32_toolchains.tar
+        ls
+        if [ $? != 0 ]; then
+          echo "download toolchain fail"
+          exit 1
+        fi
+        
+        # wget -O cdt2cmake_Linux_X64.tar.xz http://wiki.telink-semi.cn/tools_and_sdk/others/cdt2cmake_Linux_X64.tar.xz    
+        # tar xf cdt2cmake_Linux_X64.tar.xz
+        # ls
+        # if [ $? != 0 ]; then
+        #   echo "download cdt2cmake fail"
+        #   exit 1
+        # fi
+        
+    - if: ${{ steps.Restore_Cached_Toolchain.outputs.cache-hit != 'true' }}
+      name: Cache Toolchain
+      uses: actions/cache@v3
+      with:
+        path: |
+          cdt2cmake
+          # tc32
+        key: ${{ runner.os }}-toolchain-tc32
+
+    - name: download and decompression toolchain
+      run: |
+        wget -O tc32_toolchains.tar https://wiki.telink-semi.cn/tools_and_sdk/others/tc32_toolchains.tar
+        tar xf tc32_toolchains.tar
+        ls
+        if [ $? != 0 ]; then
+          echo "download toolchain fail"
+          exit 1
+        fi
+        
     - name: cmake build
       run: |
         echo "cmake building..."
@@ -80,11 +159,4 @@ jobs:
         cmake ./b85_ble_sdk -Bcmake_build -DTOOLCHAIN_PATH="`pwd`/tc32"
         echo "parameter_name ${{ github.event.inputs.target }}"
         cmake --build cmake_build --target "${{ github.event.inputs.target }}" -j16
-
-    - name: upload artifacts
-      uses: actions/upload-artifact@v3
-      with:
-        name: build_artifact
-        path: |
-          cmake_build/${{ github.event.inputs.target }}*
-        retention-days: 3
+  
