Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,77 +18,77 @@ on:
         default: '825x_ble_sample'
 
 jobs:
-  # Linux_CMake_Convert:
-  #   runs-on: ubuntu-latest
+  Linux_CMake_Convert:
+    runs-on: ubuntu-latest
     
-  #   steps:
-  #   - name: check parameters
-  #     run: |
-  #       echo "cproject ${{ github.event.inputs.cproject }}"
-  #       echo "target ${{ github.event.inputs.target }}"
+    steps:
+    - name: check parameters
+      run: |
+        echo "cproject ${{ github.event.inputs.cproject }}"
+        echo "target ${{ github.event.inputs.target }}"
 
-  #   - name: Checkout Repository
-  #     uses: actions/checkout@v4
+    - name: Checkout Repository
+      uses: actions/checkout@v4
 
-  #   - name: Restore Cached Toolchain
-  #     id: Restore_Cached_Toolchain
-  #     uses: actions/cache@v4
-  #     with:
-  #       path: |
-  #         cdt2cmake
-  #         # tc32
-  #       key: ${{ runner.os }}-toolchain-tc32
-  #       restore-keys: |
-  #         ${{ runner.os }}-toolchain-tc32
+    - name: Restore Cached Toolchain
+      id: Restore_Cached_Toolchain
+      uses: actions/cache@v4
+      with:
+        path: |
+          cdt2cmake
+          # tc32
+        key: ${{ runner.os }}-toolchain-tc32
+        restore-keys: |
+          ${{ runner.os }}-toolchain-tc32
      
-  #   - if: ${{ steps.Restore_Cached_Toolchain.outputs.cache-hit != 'true' }}
-  #     name: download and decompression toolchain
-  #     run: |
-  #       # curl -o tc32_toolchains.tar https://wiki.telink-semi.cn/tools_and_sdk/others/toolchains/tc32(1.3.0)_Linux_X64.tar
-  #       # tar xf tc32_toolchains.tar
-  #       # ls
-  #       # if [ $? != 0 ]; then
-  #       #   echo "download toolchain fail"
-  #       #   exit 1
-  #       # fi
+    - if: ${{ steps.Restore_Cached_Toolchain.outputs.cache-hit != 'true' }}
+      name: download and decompression toolchain
+      run: |
+        # curl -o tc32_toolchains.tar https://wiki.telink-semi.cn/tools_and_sdk/others/toolchains/tc32(1.3.0)_Linux_X64.tar
+        # tar xf tc32_toolchains.tar
+        # ls
+        # if [ $? != 0 ]; then
+        #   echo "download toolchain fail"
+        #   exit 1
+        # fi
         
-  #       curl -o cdt2cmake_Linux_X64.tar.xz http://wiki.telink-semi.cn/tools_and_sdk/others/cdt2cmake_Linux_X64.tar.xz    
-  #       tar xf cdt2cmake_Linux_X64.tar.xz
-  #       ls
-  #       if [ $? != 0 ]; then
-  #         echo "download cdt2cmake fail"
-  #         exit 1
-  #       fi
+        curl -o cdt2cmake_Linux_X64.tar http://wiki.telink-semi.cn/tools_and_sdk/others/cdt2cmake_Linux_X64.tar
+        tar xf cdt2cmake_Linux_X64.tar
+        ls
+        if [ $? != 0 ]; then
+          echo "download cdt2cmake fail"
+          exit 1
+        fi
         
-  #   - if: ${{ steps.Restore_Cached_Toolchain.outputs.cache-hit != 'true' }}
-  #     name: Cache Toolchain
-  #     uses: actions/cache@v4
-  #     with:
-  #       path: |
-  #         cdt2cmake
-  #         # tc32
-  #       key: ${{ runner.os }}-toolchain-tc32
+    - if: ${{ steps.Restore_Cached_Toolchain.outputs.cache-hit != 'true' }}
+      name: Cache Toolchain
+      uses: actions/cache@v4
+      with:
+        path: |
+          cdt2cmake
+          # tc32
+        key: ${{ runner.os }}-toolchain-tc32
 
-  #   - name: convert cdt2cmake
-  #     run: |
-  #       echo "convert cdt2cmake"
-  #       ./cdt2cmake/cdt2cmake ${{ github.event.inputs.cproject }}
-  #       find . -name "CMakeLists.txt"
-  #   # - name: cmake build
-  #   #   run: |
-  #   #     echo "cmake building..."
-  #   #     ls
-  #   #     cmake ./b85_ble_sdk -Bcmake_build -DTOOLCHAIN_PATH="`pwd`/tc32"
-  #   #     echo "parameter_name ${{ github.event.inputs.target }}"
-  #   #     cmake --build cmake_build --target "${{ github.event.inputs.target }}" -j16
+    - name: convert cdt2cmake
+      run: |
+        echo "convert cdt2cmake"
+        ./cdt2cmake/cdt2cmake ${{ github.event.inputs.cproject }}
+        find . -name "CMakeLists.txt"
+    # - name: cmake build
+    #   run: |
+    #     echo "cmake building..."
+    #     ls
+    #     cmake ./b85_ble_sdk -Bcmake_build -DTOOLCHAIN_PATH="`pwd`/tc32"
+    #     echo "parameter_name ${{ github.event.inputs.target }}"
+    #     cmake --build cmake_build --target "${{ github.event.inputs.target }}" -j16
 
-  #   - name: upload cmake artifacts
-  #     uses: actions/upload-artifact@v4
-  #     with:
-  #       name: cmake-files
-  #       path: |
-  #         ./**/CMakeLists.txt
-  #       retention-days: 1
+    - name: upload cmake artifacts
+      uses: actions/upload-artifact@v4
+      with:
+        name: cmake-files
+        path: |
+          ./**/CMakeLists.txt
+        retention-days: 1
 
   Windows_CMake_build:
     # runs-on: windows-latest
@@ -107,11 +107,11 @@ jobs:
     - name: Checkout Repository
       uses: actions/checkout@v4
 
-    # - name: Download and extract CMakeLists.txt files
-    #   uses: actions/download-artifact@v4
-    #   with:
-    #     name: cmake-files
-    #     path: .
+    - name: Download and extract CMakeLists.txt files
+      uses: actions/download-artifact@v4
+      with:
+        name: cmake-files
+        path: .
 
     - name: Restore Cached Toolchain
       id: Restore_Cached_Toolchain
@@ -152,8 +152,8 @@ jobs:
       run: |
         echo "cmake building..."
         export PATH=$PATH:"$(pwd)/tc32/bin"
-        find . -type f -name "*.sh"
         find . -type f -name "*.sh" -exec chmod +x {} \;
+        sed -i 's/\$2\.elf/\$1/g' b85_ble_sdk/tl_check_fw.sh
         cmake --version
         cmake b85_ble_sdk -Bb85_ble_sdk/cmake_build -G "Unix Makefiles"  -DTOOLCHAIN_PATH=$(pwd)/tc32 -DCMAKE_C_STANDARD_LIBRARIES="" -DCMAKE_CXX_STANDARD_LIBRARIES="" -DCMAKE_C_COMPILER_FORCED=TRUE -DCMAKE_CXX_COMPILER_FORCED=TRUE 
         echo "parameter_name ${{ github.event.inputs.target }}"
