Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,82 +18,82 @@ on:
         default: '825x_ble_sample'
 
 jobs:
-  # Linux_CMake_Convert:
-  #   runs-on: ubuntu-latest
+  Linux_CMake_Convert:
+    runs-on: ubuntu-latest
     
-  #   steps:
-  #   - name: check parameters
-  #     run: |
-  #       echo "cproject ${{ github.event.inputs.cproject }}"
-  #       echo "target ${{ github.event.inputs.target }}"
+    steps:
+    - name: check parameters
+      run: |
+        echo "cproject ${{ github.event.inputs.cproject }}"
+        echo "target ${{ github.event.inputs.target }}"
 
-  #   - name: Checkout Repository
-  #     uses: actions/checkout@v4
+    - name: Checkout Repository
+      uses: actions/checkout@v4
 
-  #   - name: Restore Cached Toolchain
-  #     id: Restore_Cached_Toolchain
-  #     uses: actions/cache@v4
-  #     with:
-  #       path: |
-  #         cdt2cmake
-  #         # tc32
-  #       key: ${{ runner.os }}-toolchain-tc32
-  #       restore-keys: |
-  #         ${{ runner.os }}-toolchain-tc32
+    - name: Restore Cached Toolchain
+      id: Restore_Cached_Toolchain
+      uses: actions/cache@v4
+      with:
+        path: |
+          cdt2cmake
+          # tc32
+        key: ${{ runner.os }}-toolchain-tc32
+        restore-keys: |
+          ${{ runner.os }}-toolchain-tc32
      
-  #   - if: ${{ steps.Restore_Cached_Toolchain.outputs.cache-hit != 'true' }}
-  #     name: download and decompression toolchain
-  #     run: |
-  #       # curl -o tc32_toolchains.tar https://wiki.telink-semi.cn/tools_and_sdk/others/tc32_toolchains.tar
-  #       # tar xf tc32_toolchains.tar
-  #       # ls
-  #       # if [ $? != 0 ]; then
-  #       #   echo "download toolchain fail"
-  #       #   exit 1
-  #       # fi
+    - if: ${{ steps.Restore_Cached_Toolchain.outputs.cache-hit != 'true' }}
+      name: download and decompression toolchain
+      run: |
+        # curl -o tc32_toolchains.tar https://wiki.telink-semi.cn/tools_and_sdk/others/tc32_toolchains.tar
+        # tar xf tc32_toolchains.tar
+        # ls
+        # if [ $? != 0 ]; then
+        #   echo "download toolchain fail"
+        #   exit 1
+        # fi
         
-  #       curl -o cdt2cmake_Linux_X64.tar.xz http://wiki.telink-semi.cn/tools_and_sdk/others/cdt2cmake_Linux_X64.tar.xz    
-  #       tar xf cdt2cmake_Linux_X64.tar.xz
-  #       ls
-  #       if [ $? != 0 ]; then
-  #         echo "download cdt2cmake fail"
-  #         exit 1
-  #       fi
+        curl -o cdt2cmake_Linux_X64.tar.xz http://wiki.telink-semi.cn/tools_and_sdk/others/cdt2cmake_Linux_X64.tar.xz    
+        tar xf cdt2cmake_Linux_X64.tar.xz
+        ls
+        if [ $? != 0 ]; then
+          echo "download cdt2cmake fail"
+          exit 1
+        fi
         
-  #   - if: ${{ steps.Restore_Cached_Toolchain.outputs.cache-hit != 'true' }}
-  #     name: Cache Toolchain
-  #     uses: actions/cache@v4
-  #     with:
-  #       path: |
-  #         cdt2cmake
-  #         # tc32
-  #       key: ${{ runner.os }}-toolchain-tc32
+    - if: ${{ steps.Restore_Cached_Toolchain.outputs.cache-hit != 'true' }}
+      name: Cache Toolchain
+      uses: actions/cache@v4
+      with:
+        path: |
+          cdt2cmake
+          # tc32
+        key: ${{ runner.os }}-toolchain-tc32
 
-  #   - name: convert cdt2cmake
-  #     run: |
-  #       echo "convert cdt2cmake"
-  #       ./cdt2cmake/cdt2cmake ${{ github.event.inputs.cproject }}
-  #       find . -name "CMakeLists.txt"
-  #   # - name: cmake build
-  #   #   run: |
-  #   #     echo "cmake building..."
-  #   #     ls
-  #   #     cmake ./b85_ble_sdk -Bcmake_build -DTOOLCHAIN_PATH="`pwd`/tc32"
-  #   #     echo "parameter_name ${{ github.event.inputs.target }}"
-  #   #     cmake --build cmake_build --target "${{ github.event.inputs.target }}" -j16
+    - name: convert cdt2cmake
+      run: |
+        echo "convert cdt2cmake"
+        ./cdt2cmake/cdt2cmake ${{ github.event.inputs.cproject }}
+        find . -name "CMakeLists.txt"
+    # - name: cmake build
+    #   run: |
+    #     echo "cmake building..."
+    #     ls
+    #     cmake ./b85_ble_sdk -Bcmake_build -DTOOLCHAIN_PATH="`pwd`/tc32"
+    #     echo "parameter_name ${{ github.event.inputs.target }}"
+    #     cmake --build cmake_build --target "${{ github.event.inputs.target }}" -j16
 
-  #   - name: upload cmake artifacts
-  #     uses: actions/upload-artifact@v4
-  #     with:
-  #       name: cmake-files
-  #       path: |
-  #         ./**/CMakeLists.txt
-  #       retention-days: 3
+    - name: upload cmake artifacts
+      uses: actions/upload-artifact@v4
+      with:
+        name: cmake-files
+        path: |
+          ./**/CMakeLists.txt
+        retention-days: 3
 
   Windows_CMake_Cache:
     runs-on: windows-latest
     # runs-on: windows-2019
-    # needs: Linux_CMake_Convert
+    needs: Linux_CMake_Convert
     defaults:
       run:
         shell: bash
@@ -148,15 +148,9 @@ jobs:
       run:
         shell: bash
     # runs-on: windows-2019
-    # needs: Linux_CMake_Convert
+    needs: Linux_CMake_Convert
 
     steps:
-    # - name: test gcc
-    #   run: |
-    #     /c/msys64/mingw32/bin/gcc -v --version
-    #     /c/msys64/mingw32/bin/i686-w64-mingw32-gcc -v --version
-    #     exit 0
-
     - name: check parameters
       run: |
         echo "cproject ${{ github.event.inputs.cproject }}"
@@ -165,18 +159,11 @@ jobs:
     - name: Checkout Repository
       uses: actions/checkout@v4
 
-    # - name: Download and extract CMakeLists.txt files
-    #   uses: actions/download-artifact@v4
-    #   with:
-    #     name: cmake-files
-    #     path: .
-
-    # - name: Move extracted files to original location
-    #   run: |
-    #     ls
-    #     ls cmake-files
-    #     mv cmake-files/**/CMakeLists.txt .
-    #     find . -name "CMakeLists.txt"
+    - name: Download and extract CMakeLists.txt files
+      uses: actions/download-artifact@v4
+      with:
+        name: cmake-files
+        path: .
 
     - name: Restore Cached Toolchain
       id: Restore_Cached_Toolchain
@@ -202,15 +189,7 @@ jobs:
           echo "download toolchain fail"
           exit 1
         fi
-        
-        # curl -o cdt2cmake_Linux_X64.tar.xz http://wiki.telink-semi.cn/tools_and_sdk/others/cdt2cmake_Linux_X64.tar.xz    
-        # tar xf cdt2cmake_Linux_X64.tar.xz
-        # ls
-        # if [ $? != 0 ]; then
-        #   echo "download cdt2cmake fail"
-        #   exit 1
-        # fi
-        
+         
     - if: ${{ steps.Restore_Cached_Toolchain.outputs.cache-hit != 'true' }}
       name: Cache Toolchain
       uses: actions/cache@v4
@@ -220,16 +199,6 @@ jobs:
           tc32
         key: ${{ runner.os }}-toolchain-tc32
 
-          # echo "cmake building..."
-        # ls
-        # set VERBOSE=1
-        # export VERBOSE=1
-        # $(pwd)/tc32/bin/tc32-elf-gcc.exe --version
-        # $(pwd)/tc32/bin/tc32-elf-gcc.exe -c test.c -o test.o
-        # $(pwd)/tc32/bin/tc32-elf-gcc -fpack-struct -fshort-enums -O2 -D__PROJECT_8258_BLE_SAMPLE__=1 -DCHIP_TYPE=CHIP_TYPE_825x -std=gnu99 -fshort-wchar -fms-extensions -finline-small-functions -ffunction-sections -fdata-sections -Wall -c b85_ble_sdk/application/app/usbaud.c -o test
-        # cmake -DCMAKE_C_COMPILER_WORKS=1 -DCMAKE_CXX_COMPILER_WORKS=1 -G "Unix Makefiles" b85_ble_sdk -Bcmake_build -DTOOLCHAIN_PATH=$(pwd)/tc32
-        # echo "parameter_name ${{ github.event.inputs.target }}"
-        # cmake --build cmake_build --target "${{ github.event.inputs.target }}"
     - name: cmake build
       shell: bash
       run: |
@@ -238,7 +207,5 @@ jobs:
         cmake --version
         cmake -DCMAKE_C_STANDARD_LIBRARIES="" -DCMAKE_CXX_STANDARD_LIBRARIES="" -DCMAKE_C_COMPILER_FORCED=TRUE -DCMAKE_CXX_COMPILER_FORCED=TRUE -DCMAKE_ASM_COMPILER_FORCED=TRUE  -DCMAKE_C_COMPILER_WORKS=1 -DCMAKE_CXX_COMPILER_WORKS=1 -G "Unix Makefiles" b85_ble_sdk -Bcmake_build -DTOOLCHAIN_PATH=$(pwd)/tc32
         echo "parameter_name ${{ github.event.inputs.target }}"
-        cmake --build cmake_build --target "${{ github.event.inputs.target }}"
-        # chmod +x test.sh
-        # ./test.sh
+        cmake --build cmake_build --target "${{ github.event.inputs.target }}" -j16
         
